In [1]:
import numpy as np

In [2]:
myArr=np.arange(0,15)

In [3]:
myArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
myArr[4]

4

In [6]:
myArr[3:11]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
myArr[3:7]=-11

In [8]:
myArr

array([  0,   1,   2, -11, -11, -11, -11,   7,   8,   9,  10,  11,  12,
        13,  14])

In [9]:
myArr2=np.arange(0,24)

In [10]:
myArr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
sliceArr=myArr2[3:15]

In [12]:
sliceArr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
sliceArr[:]=54

In [14]:
sliceArr

array([54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54])

In [16]:
myArr2

array([ 0,  1,  2, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
ornekArr=np.arange(0,24)

In [19]:
ornekArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
ornekArrCopy=ornekArr.copy()

In [21]:
ornekArrCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
ornekArrCopySlice=ornekArrCopy[6:24]

In [23]:
ornekArrCopySlice[:]=804

In [24]:
ornekArrCopySlice

array([804, 804, 804, 804, 804, 804, 804, 804, 804, 804, 804, 804, 804,
       804, 804, 804, 804, 804])

In [26]:
ornekArrCopy

array([  0,   1,   2,   3,   4,   5, 804, 804, 804, 804, 804, 804, 804,
       804, 804, 804, 804, 804, 804, 804, 804, 804, 804, 804])

matrix

In [27]:
matrixList=[[10,20,30],[40,50,60],[70,80,90]]

In [28]:
myMatrix=np.array(matrixList)

In [29]:
myMatrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [30]:
myMatrix[0][1]

20

In [31]:
myMatrix[1,2]

60

In [33]:
myMatrix[1:,2:]

array([[60],
       [90]])

In [35]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [36]:
yeniMatrix = np.array(yeniListe)

In [37]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

operasyonlar

In [41]:
yeniBirDizi = np.random.randint(1,100,(5,5))

In [42]:
yeniBirDizi

array([[98, 32, 82, 37, 70],
       [40, 41, 98, 55,  9],
       [48, 59, 33, 15,  8],
       [94, 54, 94,  9, 87],
       [97, 99, 82, 21, 68]])

In [43]:
yeniBirDizi > 24

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False,  True],
       [ True,  True,  True, False,  True]])

In [44]:
sonucDizisi = yeniBirDizi > 24

In [45]:
sonucDizisi

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False,  True],
       [ True,  True,  True, False,  True]])

In [46]:
yeniBirDizi[sonucDizisi]

array([98, 32, 82, 37, 70, 40, 41, 98, 55, 48, 59, 33, 94, 54, 94, 87, 97,
       99, 82, 68])

In [47]:
yeniBirDizi[yeniBirDizi > 24]

array([98, 32, 82, 37, 70, 40, 41, 98, 55, 48, 59, 33, 94, 54, 94, 87, 97,
       99, 82, 68])

In [48]:
sonDizi = np.arange(0,24)

In [49]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [51]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [52]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [53]:
sonDizi / sonDizi

C:\Users\Celal\AppData\Local\Temp\ipykernel_7592\1312094733.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [54]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [55]:
np.max(sonDizi)

23

In [56]:
np.min(sonDizi)

0